sources:
  - &server !Sftp
    host: '13.211.134.29'
    user: ec2-user
    key: /home/main/.ssh/carson-admin.pem
    # or, potentially in the future
    # key: s3://a-special-bucket/key.pem
  - &bucket !S3
    region: ap-southeast-2
    bucket: file-copier-test
destinations:
  - *server
  - *bucket
jobs:
  - file: hello.txt
    from: *server
    to: *bucket
